// Generated by Haxe 4.0.0-rc.2+77068e10c
(function () { "use strict";
var BaseMain = function() { };
BaseMain.main = function() {
	var iter = HxOverrides.iter([2,3,4,5]);
	var elem = new tom_util_MapIter(iter,function(i) {
		return i * 4;
	});
	while(elem.hasNext()) {
		var elem1 = elem.next();
		console.log("tests/BaseMain.hx:7:",elem1);
	}
};
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var tom_util_MapIter = function(iter,map) {
	this.iter = iter;
	this.map = map;
};
tom_util_MapIter.prototype = {
	hasNext: function() {
		return this.iter.hasNext();
	}
	,next: function() {
		return this.map(this.iter.next());
	}
};
BaseMain.main();
})();
